version: "3.8"
services:
  app: &app_base
    build:
      context: .
      dockerfile: Dockerfile.aws
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      NODE_ENV: development
      RAILS_MASTER_KEY: xxxxxxxx
    command: bash -c "bundle install && bin/yarn && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
volumes:
  bundle:
  node_modules:
