version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.aws
    environment:
      RAILS_ENV: production
      RACK_ENV: production
      NODE_ENV: production
      RAILS_LOG_TO_STDOUT: 'true'
      RAILS_MASTER_KEY: 9ea92f8762cfc2a32cfa0ac04156f7f4
      APP_DATABASE_HOST: db
      APP_DATABASE_NAME: kon-yu-production
      APP_DATABASE_USERNAME: root
      APP_DATABASE_PASSWORD: password
    command: bash -c "bundle install && bin/yarn && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql
    environment:
      # MARIADB_HOST: db
      MARIADB_ROOT_PASSWORD: password
      # MARIADB_DATABASE: dabase
      MARIADB_USER: mysql
      MARIADB_PASSWORD: password
      TZ: Asia/Tokyo

volumes:
  db:
